services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/portfolio.db:/app/portfolio.db
    environment:
      - JWT_SECRET=your-secret-key-here
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend